# Generated by Django 6.0.2 on 2026-04-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('items_listed', models.PositiveIntegerField(default=0)),
                ('completed_sales', models.PositiveIntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('response_time', models.CharField(blank=True, default='', max_length=100)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=False)),
                ('is_active_seller', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authentication.student')),
            ],
        ),
    ]
