# Generated by Django 6.0.2 on 2026-05-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to='announcements/%Y/%m/%d/'),
        ),
    ]
