# Generated by Django 6.0.2 on 2026-03-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='announcements.announcement')),
            ],
            options={
                'db_table': 'favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'announcement'], name='favorite_user_id_332662_idx')],
                'unique_together': {('user_id', 'announcement')},
            },
        ),
    ]
