# Generated by Django 6.0.2 on 2026-04-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_allow_chat_announcement_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
