# Generated by Django 6.0.2 on 2026-04-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('good', 'Good'), ('damaged', 'Damaged')], max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
