# Generated by Django 6.0.2 on 2026-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_university_university_name_65a7d2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
