# Generated by Django 6.0.2 on 2026-04-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='student_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
