# Generated by Django 6.0.2 on 2026-04-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_status'),
    ]

    operations = [
        # ── ORIGINAL CODE (commented out — breaks PostgreSQL, cannot cast integer to uuid) ──
        # migrations.AlterField(
        #     model_name='announcement',
        #     name='student_id',
        #     field=models.UUIDField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='comment',
        #     name='user_id',
        #     field=models.UUIDField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='favorite',
        #     name='user_id',
        #     field=models.UUIDField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='review',
        #     name='user_id',
        #     field=models.UUIDField(db_index=True),
        # ),

        # ── FIX: Drop and recreate columns as UUID (PostgreSQL-compatible) ──
        migrations.RunSQL(
            sql="""
                ALTER TABLE announcement DROP COLUMN IF EXISTS student_id;
                ALTER TABLE announcement ADD COLUMN student_id uuid;
                CREATE INDEX IF NOT EXISTS announcemen_student_58c7f2_idx ON announcement (student_id);
                ALTER TABLE comment DROP COLUMN IF EXISTS user_id;
                ALTER TABLE comment ADD COLUMN user_id uuid;
                ALTER TABLE favorite DROP COLUMN IF EXISTS user_id;
                ALTER TABLE favorite ADD COLUMN user_id uuid;
                ALTER TABLE review DROP COLUMN IF EXISTS user_id;
                ALTER TABLE review ADD COLUMN user_id uuid;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='announcement',
                    name='student_id',
                    field=models.UUIDField(db_index=True),
                ),
                migrations.AlterField(
                    model_name='comment',
                    name='user_id',
                    field=models.UUIDField(db_index=True),
                ),
                migrations.AlterField(
                    model_name='favorite',
                    name='user_id',
                    field=models.UUIDField(db_index=True),
                ),
                migrations.AlterField(
                    model_name='review',
                    name='user_id',
                    field=models.UUIDField(db_index=True),
                ),
            ],
        ),
    ]