# Generated by Django 6.0.2 on 2026-05-20 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_announcement_student_id_alter_comment_user_id_and_more'),
        ('universities', '0002_university_latitude_university_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='universities.university'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
