# Generated by Django 6.0.2 on 2026-05-20 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_announcement_student_id_alter_comment_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Arnaque'), ('inappropriate', 'Contenu inapproprié'), ('fake', 'Faux produit / fausse annonce'), ('offensive', 'Contenu offensant'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('ignored', 'Ignoré')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='announcements.announcement')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_9e629c_idx'), models.Index(fields=['announcement'], name='report_announc_8ac272_idx'), models.Index(fields=['reporter_id'], name='report_reporte_250e97_idx')],
            },
        ),
    ]
