# Generated by Django 6.0.2 on 2026-05-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_alter_announcement_university_alter_photo_position_and_more'),
        ('announcements', '0009_report'),
    ]

    operations = [
    ]
