# Generated by Django 6.0.2 on 2026-05-26 01:56

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('announcements', '0010_alter_announcement_university_alter_photo_position_and_more'),
    ]
    operations = []