# Generated by Django 6.0.2 on 2026-05-21 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_merge_20260521_1420'),
        ('universities', '0003_fix_report_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_status_d9f732_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_categor_bd962e_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_created_cbc578_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_univers_4556a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='favorite_user_id_332662_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photo_announc_f1bb80_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_status_9e629c_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_announc_8ac272_idx',
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'created_at'], name='announcemen_status_9679f5_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category_id'], name='announcemen_categor_bd962e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['university_id'], name='announcemen_univers_4556a8_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user_id', 'announcement_id'], name='favorite_user_id_332662_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['announcement_id', 'position'], name='photo_announc_f1bb80_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='report_status_d62165_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['announcement_id'], name='report_announc_8ac272_idx'),
        ),
    ]
