# Generated by Django 6.0.2 on 2026-05-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_merge_20260521_1512'),
        ('announcements', '0011_fix_report_index'),
    ]

    operations = [
    ]
