# Generated by Django 6.0.2 on 2026-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_delete_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
