# Generated by Django 6.0.2 on 2026-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_announcement_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('draft', 'Draft'), ('archived', 'Archived'), ('reserved', 'Reserved')], default='active', max_length=20),
        ),
    ]
