# Generated by Django 6.0.2 on 2026-05-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_conversation_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_deleted_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_deleted_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
