# Generated by Django 6.0.2 on 2026-04-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('new_message', 'New message'), ('new_photo_message', 'New photo message'), ('new_review', 'New review'), ('new_favorite', 'Added to favorites'), ('new_comment', 'New comment'), ('comment_reply', 'Reply to your comment')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('announcement_id', models.IntegerField(blank=True, null=True)),
                ('conversation_id', models.IntegerField(blank=True, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('message_preview', models.TextField(blank=True)),
                ('message_image_url', models.URLField(blank=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_full_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_366c29_idx'), models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_d569bc_idx')],
            },
        ),
    ]
