# Generated by Django 6.0.2 on 2026-03-11 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('domain', models.CharField(help_text='ex: univ-oran.dz', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
