# Generated by Django 6.0.2 on 2026-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
