# Generated by Django 6.0.2 on 2026-05-21 23:22
# Generated by Django 6.0.2 on 2026-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_latitude_university_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='university_name_65a7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['domain'], name='university_domain_aa8c15_idx'),
        ),
    ]